name: local

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
